### 注册服务实例
POST http://localhost:7010/smilodon/register
Content-Type: application/json

{
  "serviceId": "SERVER-PERSON",
  "instanceId": "serverperson7003",
  "host": "127.0.0.1",
  "port":7003,
  "secure":false
}

### 注册服务实例
POST http://localhost:7010/smilodon/register
Content-Type: application/json

{
  "serviceId": "SERVER-BOOK",
  "instanceId": "serverbook6001",
  "host": "127.0.0.1",
  "port":6001,
  "secure":false
}

###
GET http://localhost:8001
Accept: application/json


### 获取注册服务列表
GET http://localhost:7010/smilodon/discovery
Accept: application/json

### 根据注册服务获取实例列表
GET http://localhost:7010/smilodon/discovery/SERVER-PERSON
Accept: application/json

### 获取订阅服务列表
GET http://localhost:7010/smilodon/subscribe
Accept: application/json

### 订阅服务
POST http://localhost:7010/smilodon/subscribe
Accept: application/json

http://192.168.43.149:6001

### 取消订阅服务
POST http://localhost:7010/smilodon/unsubscribe
Accept: application/json

http://192.168.43.149:6001

###
GET http://localhost:7010/smilodon/serviceregistry
Accept: application/json

### actuator
GET http://localhost:7010/actuator
Accept: application/json


### 健康检查
GET http://localhost:7010/actuator/health
Accept: application/json